# Generated by Django 5.0.4 on 2026-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_onboarding_completed_customuser_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2),
        ),
    ]
