# Generated by Django 5.0.4 on 2026-04-20 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], max_length=10)),
                ('emotion', models.CharField(blank=True, choices=[('calm', 'Calm'), ('confident', 'Confident'), ('fearful', 'Fearful'), ('greedy', 'Greedy'), ('anxious', 'Anxious'), ('fomo', 'FOMO'), ('revenge', 'Revenge'), ('neutral', 'Neutral')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades_trade',
                'ordering': ['-entry_time'],
            },
        ),
    ]
