import { getTranslations } from "next-intl/server";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "terms" });
  return { title: t("title") };
}

export default async function TerminosPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "terms" });
  const isEn = locale === "en";

  return (
    <div className="bg-light min-h-screen">
      <section className="py-20 lg:py-28 border-b border-black/[0.08]">
        <div className="max-w-[720px] mx-auto px-6 lg:px-10">
          <p className="eyebrow mb-4">{t("eyebrow")}</p>
          <h1 className="font-sans text-[40px] lg:text-[52px] font-bold text-text leading-[1.05] tracking-[-0.02em]">
            {t("heading")}
          </h1>
          <p className="font-mono text-[11px] text-text-muted mt-4">{t("updated")}</p>
        </div>
      </section>

      <section className="py-16 lg:py-20">
        <div className="max-w-[720px] mx-auto px-6 lg:px-10 prose-tradalyst">
          {isEn ? (
            <>
              <h2>1. Scope and Acceptance</h2>
              <p>
                These Terms and Conditions of Use govern access to and use of Tradalyst, a trading journal tool
                with artificial intelligence analysis (&ldquo;the Service&rdquo;). By registering or using the Service,
                you accept these Terms in full. If you do not agree, do not use the Service.
              </p>

              <h2>2. The Service</h2>
              <p>
                Tradalyst is a web platform that allows traders to log their trades, add reasoning and emotional
                state, and receive AI-generated behavioural analysis. The Service is provided on a
                &ldquo;best effort&rdquo; basis without guaranteed uptime. No Service Level Agreement (SLA) is
                guaranteed on the free plan. Tradalyst reserves the right to modify, suspend or discontinue the
                Service with reasonable prior notice to users.
              </p>

              <h2>3. Registration and Account</h2>
              <ul>
                <li>
                  You must be at least 18 years old, or of the minimum legal age in your country, to use this
                  Service.
                </li>
                <li>
                  You are responsible for maintaining the confidentiality of your password and for all activities
                  carried out under your account.
                </li>
                <li>
                  Only one account per person is permitted. Creating multiple accounts may result in all of them
                  being suspended.
                </li>
                <li>
                  Notify <a href="mailto:hola@tradalyst.com">hola@tradalyst.com</a> immediately if you suspect
                  your account has been compromised.
                </li>
              </ul>

              <h2>4. Acceptable Use</h2>
              <p>The following are strictly prohibited:</p>
              <ul>
                <li>Using the Service for illegal activities or activities that infringe third-party rights.</li>
                <li>Attempting to access other users&apos; accounts or trade data.</li>
                <li>Reverse engineering, decompiling or disassembling any component of the Service.</li>
                <li>
                  Using bots, scrapers or automated tools to access the Service without prior written
                  authorisation.
                </li>
              </ul>

              <h2>5. Important Financial Disclaimer</h2>
              <p>
                Tradalyst is a trade logging and analysis tool. It is <strong>NOT</strong> a financial adviser,
                regulated investment platform, or investment advisory service. The information and analyses
                generated by artificial intelligence do <strong>NOT</strong> constitute regulated financial
                advice. Investment decisions are the sole responsibility of the user. Use of the Service does not
                guarantee trading profitability or positive results.
              </p>

              <h2>6. Plans and Payments</h2>
              <ul>
                <li>
                  <strong>Free Plan:</strong> no cost, with basic journal and analysis features.
                </li>
                <li>
                  <strong>Pro Plan:</strong> €9.99/month, with full access to AI analysis, advanced reports and
                  premium features.
                </li>
                <li>New Pro Plan users receive a 7-day free trial.</li>
                <li>
                  The subscription renews automatically on a monthly basis until cancelled by the user.
                </li>
                <li>
                  You can cancel at any time from Settings → Account. Cancellation takes effect at the end of the
                  current billing period.
                </li>
                <li>No refunds are issued for periods already billed.</li>
              </ul>

              <h2>7. Intellectual Property</h2>
              <p>
                The code, design, brand and other elements of the Service are the property of the Tradalyst
                developer. Trade data and content entered by the user are the property of the user. Tradalyst
                claims no ownership over user-generated content, and does not sell or transfer it to third
                parties.
              </p>

              <h2>8. Limitation of Liability</h2>
              <p>
                Tradalyst shall not be liable for financial losses, direct or indirect damages arising from the
                use of the Service or trading decisions made based on the generated analyses. The Service is
                provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties of any kind regarding the
                accuracy of analyses or trading results.
              </p>

              <h2>9. Cancellation and Account Deletion</h2>
              <p>
                You may delete your account at any time from Settings → Account. After deletion, your personal
                data will be permanently deleted within a maximum of 30 days. Tradalyst may suspend or cancel
                accounts that breach these Terms, notifying the user where possible.
              </p>

              <h2>10. Governing Law and Jurisdiction</h2>
              <p>
                These Terms are governed by Spanish law. For any dispute arising from the use of the Service,
                the parties submit to the courts and tribunals of Málaga, Spain, without prejudice to any
                mandatory consumer protection forum that may apply to the user.
              </p>
            </>
          ) : (
            <>
              <h2>1. Objeto y aceptación</h2>
              <p>
                Los presentes Términos y Condiciones de Uso regulan el acceso y uso de Tradalyst, una
                herramienta de diario de trading con análisis de inteligencia artificial (&ldquo;el Servicio&rdquo;). Al
                registrarte o utilizar el Servicio, aceptas estos Términos en su totalidad. Si no estás de
                acuerdo, no uses el Servicio.
              </p>

              <h2>2. El Servicio</h2>
              <p>
                Tradalyst es una plataforma web que permite a traders registrar sus operaciones, añadir
                razonamiento y estado emocional, y recibir análisis de comportamiento generados por IA. El
                Servicio se presta en régimen de &ldquo;mejor esfuerzo&rdquo; sin garantía de disponibilidad continua. En
                el plan gratuito no existe Acuerdo de Nivel de Servicio (SLA) garantizado. Tradalyst se reserva
                el derecho a modificar, suspender o interrumpir el Servicio con aviso previo razonable a los
                usuarios.
              </p>

              <h2>3. Registro y cuenta</h2>
              <ul>
                <li>
                  Debes ser mayor de 18 años, o mayor de la edad legal aplicable en tu país, para usar este
                  Servicio.
                </li>
                <li>
                  Eres responsable de mantener la confidencialidad de tu contraseña y de todas las actividades
                  realizadas bajo tu cuenta.
                </li>
                <li>
                  Sólo se permite una cuenta por persona. La creación de cuentas múltiples puede resultar en la
                  suspensión de todas ellas.
                </li>
                <li>
                  Notifica inmediatamente a{" "}
                  <a href="mailto:hola@tradalyst.com">hola@tradalyst.com</a> si sospechas que tu cuenta ha sido
                  comprometida.
                </li>
              </ul>

              <h2>4. Uso aceptable</h2>
              <p>Está estrictamente prohibido:</p>
              <ul>
                <li>
                  Usar el Servicio para actividades ilegales o que vulneren derechos de terceros.
                </li>
                <li>Intentar acceder a las cuentas u operaciones de otros usuarios.</li>
                <li>
                  Realizar ingeniería inversa, descompilar o desensamblar cualquier componente del Servicio.
                </li>
                <li>
                  Usar bots, scrapers o herramientas automatizadas para acceder al Servicio sin autorización
                  previa por escrito.
                </li>
              </ul>

              <h2>5. Aviso financiero importante</h2>
              <p>
                Tradalyst es una herramienta de registro y análisis de operaciones. <strong>NO</strong> es un
                asesor financiero, ni una plataforma de inversión regulada, ni ofrece asesoramiento de
                inversión. La información y los análisis generados por la inteligencia artificial{" "}
                <strong>NO</strong> constituyen asesoramiento financiero regulado. Las decisiones de inversión
                son responsabilidad exclusiva del usuario. El uso del Servicio no garantiza rentabilidad ni
                resultados positivos en trading.
              </p>

              <h2>6. Planes y pagos</h2>
              <ul>
                <li>
                  <strong>Plan Gratuito:</strong> sin coste, con funcionalidades básicas de diario y análisis.
                </li>
                <li>
                  <strong>Plan Pro:</strong> €9,99/mes, con acceso completo a análisis de IA, reportes avanzados
                  y funcionalidades premium.
                </li>
                <li>Los nuevos usuarios del Plan Pro disponen de 7 días de prueba gratuita.</li>
                <li>
                  La suscripción se renueva automáticamente de forma mensual hasta que el usuario la cancele.
                </li>
                <li>
                  Puedes cancelar en cualquier momento desde Configuración → Cuenta. La cancelación entra en
                  vigor al final del período de facturación en curso.
                </li>
                <li>No se realizan reembolsos de períodos ya facturados.</li>
              </ul>

              <h2>7. Propiedad intelectual</h2>
              <p>
                El código, diseño, marca y demás elementos del Servicio son propiedad del desarrollador de
                Tradalyst. Los datos de operaciones y el contenido introducido por el usuario son propiedad del
                usuario. Tradalyst no reivindica ningún derecho de propiedad sobre el contenido generado por el
                usuario, ni lo vende ni cede a terceros.
              </p>

              <h2>8. Limitación de responsabilidad</h2>
              <p>
                Tradalyst no será responsable de pérdidas financieras, daños directos o indirectos derivados
                del uso del Servicio o de las decisiones de trading tomadas basándose en los análisis
                generados. El Servicio se presta &ldquo;tal cual&rdquo; y &ldquo;según disponibilidad&rdquo;, sin garantías de
                ningún tipo sobre la exactitud de los análisis o los resultados en trading.
              </p>

              <h2>9. Cancelación y eliminación de cuenta</h2>
              <p>
                Puedes eliminar tu cuenta en cualquier momento desde Configuración → Cuenta. Tras la
                eliminación, tus datos personales serán borrados de forma permanente en un plazo máximo de 30
                días. Tradalyst puede suspender o cancelar cuentas que incumplan estos Términos, notificando al
                usuario cuando sea posible.
              </p>

              <h2>10. Legislación aplicable y jurisdicción</h2>
              <p>
                Los presentes Términos se rigen por la legislación española. Para cualquier controversia
                derivada del uso del Servicio, las partes se someten a los juzgados y tribunales de la ciudad
                de Málaga (España), sin perjuicio del fuero que pudiera corresponder al usuario en su condición
                de consumidor.
              </p>
            </>
          )}
        </div>
      </section>
    </div>
  );
}
